version: "3.8"

services:
  db:
    image: mysql/mysql-server:latest
    container_name: lab-my-mysql
    restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_DATABASE=labDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=labPW
      - MYSQL_ROOT_PASSWORD=labPW
    
    volumes:
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
      - 'lab_data:/var/lib/mysql'
      

volumes: # Define the named volumes
  lab_data:

networks: # Define the custom network
  hotel_network:
    name: 'lab_network'
    driver: bridge